### ISSUE TITLE
2 typos

### ISSUE THREAD

**Issue by richardson-marc** [platform9/pf9-ui-plugin#689]
minor issue, but it would improve the look of the UI:
src/app/plugins/kubernetes/components/onboarding/ClusterSetup.tsx "start running some appications"
	src/app/plugins/kubernetes/components/onboarding/PodSetup.tsx "fist Kubernetes"

I tried to open a branch and get a PR in, but this does not seem to be open to public contributions, which is fine...

**Comment by jruddell** [comment]
Hi Marc! Thanks for submitting an issue! We are not ready at the moment to accept PR's externally, but will take your feedback into account for planned work in onboarding.

**Comment by jruddell** [comment]
Hi @richardson-marc! Thanks for submitting an issue! We are not ready at the moment to accept PR's externally, but will take your feedback into account for planned work in onboarding. 

Can you explain a little more in detail what these desired changes are? E.g. in `ClusterSetup` are you asking to change the title of the section to "Start running some applications"?
